#!/bin/bash

cd ../src
gcc -I./ev3dev-c/source/ev3 -pthread -O3 -std=gnu99 -W -Wno-comment -c small_arena.c -o small_arena.o
gcc small_arena.o grab_droite.o grab_gauche.o tourner_droite.o tourner_gauche.o avancer_dst.o reculer_dst.o  demi_tour.o mes_sonar.o bouger_sonar.o poser_balle.o attraper_balle_init.o mes_sonar_fast.o avancer_dst_sonar.o -Wall -lm -lev3dev-c -pthread -lbluetooth -o ../executables/small_arena 

gcc -I./ev3dev-c/source/ev3 -pthread -O3 -std=gnu99 -W -Wno-comment -c large_arena.c -o large_arena.o
gcc large_arena.o grab_droite.o grab_gauche.o tourner_droite.o tourner_gauche.o avancer_dst.o reculer_dst.o  demi_tour.o mes_sonar.o bouger_sonar.o poser_balle.o attraper_balle_init.o mes_sonar_fast.o avancer_dst_sonar.o -Wall -lm -lev3dev-c -pthread -lbluetooth -o ../executables/large_arena 

echo "Second compilation done"

