#!/bin/bash
cd ../src
list=`ls|cut -d'.' -f1|sort -u`
for i in $list;
do
		arm-linux-gnueabi-gcc -I../../../ev3 -pthread -O3 -std=gnu99 -W  -Wno-comment -c "$i".c -o "$i".o
done
echo "First compilation done."
